[profile.default]
src = "src"
out = "out"
libs = ["lib"]
no_match_coverage = "^(script/|test/|utils/|mocks/)"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
